### ISSUE TITLE
More emphasis on the x-axis

### ISSUE THREAD

**Issue by YilmazKadir** [naver-ai/rope-vit#13]
Hi,

In my application area, I have the hypothesis that the x-axis has much more importance than the y-axis for positional encoding. In your opinion, would it make sense to give more dimensions for the x-axis positional encodings than the y-axis instead of making a 50-50 split here?
https://github.com/naver-ai/rope-vit/blob/2e801b6a5cdb4a7a8d95ed555aef5645b58044df/self-attn/rope_self_attn.py#L42

**Comment by bhheo** [comment]
Hi

Yes. Your idea makes sense to me. 

When you use more dimensions for x-axis, the attention is forced to use more x-axis for qk multiplication.
In Fourier aspect, it would improve resolution of x-axis localization, i.e. x-axis position information can be more sharp and accurate than original.

I think it’s a good idea and worth trying.
I hope you achieve great results!

**Comment by Jinjing98** [comment]
Hi Heo, 
May I ask a question as a follow up: this 'unequal' ratio setting across axis would only work for axial-rope rather than rope_mixed, right?

Best regards,
