### ISSUE TITLE
Error in backward

### ISSUE THREAD

**Issue by FiorenzoParascandolo1** [naver-ai/rope-vit#14]
I got this error during backward:

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [CUDAComplexFloatType [8, 2, 4096, 2]], which is output 0 of ViewAsComplexBackward0, is at version 2; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

I'm using standard hyperparameters

**Comment by bhheo** [comment]
Hi

I need information to solve the error
Could you provide more details about your case to reproduce the error?

1. Which training script did you use, `deit` or `SwinTransformer`?
2. What is the version of PyTorch (`torch.__version__`)?

If you provide this information, I will try to reproduce the error and debug it

**Comment by FiorenzoParascandolo1** [comment]
1. I am using class `class RoPEAttention(Attention)` from `self-attn/rope_self_attn.py` inside my custom vision transformer. Specifically, each instances of the RoPEAttention takes in input a tensor: [8, 4097, 8] with two heads, for this reason the shape of the tensor which trigger the erros is [8, 2, 4096, 2] (I notice that the rotary positional embedding is applied to all patches which are not the [CLS] token)
2. `2.5.1+cu124`

**Comment by bhheo** [comment]
I have reproduced your error in `torch==2.5.0` with minimum test code:
```python
import torch
from rope_self_attn import RoPEAttention

attn = RoPEAttention(8,2)
out = attn(torch.randn(8,4097,8))
out.sum().backward()
```
I think this error only happens in the recent torch version
I have never seen this in `torch==1.xx`

The error is caused by 
https://github.com/naver-ai/rope-vit/blob/c6aa201ee795daa4f841e2f9585164bb23a0b819/self-attn/rope_self_attn.py#L143

So, I modified it to
https://github.com/naver-ai/rope-vit/blob/ce85c2e56c5ff3aadc10e1a849872081f7b86293/self-attn/rope_self_attn.py#L143-L145

After this change, the above test code no longer produces the error

I have committed this change
Please check and let me know if your error is not solved

Thank you for reporting the error

**Comment by FiorenzoParascandolo1** [comment]
The code works but I have an other concern. 
At the beginning of the forward the line: 

`B, N, C = x.shape`

stands for [Batch Size, Sequence Length, Channels], but in

```
 q_rope, k_rope = apply_rotary_emb(q[:, :, 1:], k[:, :, 1:], freqs_cis=freqs_cis) 
 q = torch.cat((q[:, :, :1], q_rope), dim=2) 
 k = torch.cat((k[:, :, :1], k_rope), dim=2) 
```

it seems that you apply the rotary embedding to queries and keys starting from the first channel. If the intention is to apply the rotary emebddings to all patches that are not the [CLS] token the code should be changed as follows:

```
 q_rope, k_rope = apply_rotary_emb(q[:, 1:, :], k[:, 1:, :], freqs_cis=freqs_cis) 
 q = torch.cat((q[:, 0, :].unsqueeze(dim=1), q_rope), dim=1) 
 k = torch.cat((k[:, 0, :].unsqueeze(dim=1), k_rope), dim=1) 
```

**Comment by bhheo** [comment]
At the beginning, the code changes dimension config at the line 126 and 127

https://github.com/naver-ai/rope-vit/blob/ce85c2e56c5ff3aadc10e1a849872081f7b86293/self-attn/rope_self_attn.py#L125-L127

The dimension for q, k is `[B head N C//head]`
Thus, `[:, :, 1:]` is correct implementation, which is the same as `[:, :, 1:, :] `

**Comment by FiorenzoParascandolo1** [comment]
thanks you can close!
