### ISSUE TITLE
many errors in the self-attn/rope_self_attn.py script

### ISSUE THREAD

**Issue by yuanzhi-zhu** [naver-ai/rope-vit#2]
Hi there,

I just noticed that there are several typos and errors in the self-attn/rope_self_attn.py script.

eg 
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L149 is redundant
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L111 `self.` is missing for `freqs`

It would be great if you can help clean all bugs in the script.

Additionally, I would like to ask the intention for https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L140
it looks like the condition is always set to true..

**Comment by bhheo** [comment]
Hi @yuanzhi-zhu 

Thank you for noticing the bugs.

They are fixed in c6aa201
self-attn code is runnable now
Please check the new commit.

Following lines are used for different input-size such as `256x256` or `386x386`
https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L134-L136

https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L140-L141

If you have any further questions please let me know

**Comment by yuanzhi-zhu** [comment]
Thanks for your quick reply!

https://github.com/naver-ai/rope-vit/blob/2df6a9654645ea61b872c0a2b765df092ec4bee4/self-attn/rope_self_attn.py#L140

I donot really understand the reasoning behind x.shape[1] - 1, 

For the function `init_t_xy`, if the inputs are both `math.sqrt(255)`, which is not int, the returned `tx` will be:

> tensor([ 0.0000,  1.0000,  2.0000,  3.0000,  4.0000,  5.0000,  6.0000,  7.0000,
>          8.0000,  9.0000, 10.0000, 11.0000, 12.0000, 13.0000, 14.0000, 15.0000,
>          0.0313,  1.0313,  2.0313,  3.0313,  4.0313,  5.0313,  6.0313,  7.0313,
>          8.0313,  9.0313, 10.0313, 11.0313, 12.0313, 13.0313, 14.0313, 15.0313,
>          0.0626,  1.0626,  2.0626,  3.0626,  4.0626,  5.0626,  6.0626,  7.0626,
>          8.0626,  9.0626, 10.0626, 11.0626, 12.0626, 13.0626, 14.0626, 15.0626,
>          0.0938,  1.0938,  2.0938,  3.0938,  4.0938,  5.0938,  6.0938,  7.0938,
>          8.0938,  9.0938, 10.0938, 11.0938, 12.0938, 13.0938, 14.0938, 15.0938,
>          0.1251,  1.1251,  2.1251,  3.1251,  4.1251,  5.1251,  6.1251,  7.1251,
>          8.1251,  9.1251, 10.1251, 11.1251, 12.1251, 13.1251, 14.1251, 15.1251,
>          0.1564,  1.1564,  2.1564,  3.1564,  4.1564,  5.1564,  6.1564,  7.1564,
>          8.1564,  9.1564, 10.1564, 11.1564, 12.1564, 13.1564, 14.1564, 15.1564,
>          0.1877,  1.1877,  2.1877,  3.1877,  4.1877,  5.1877,  6.1877,  7.1877,
>          8.1877,  9.1877, 10.1877, 11.1877, 12.1877, 13.1877, 14.1877, 15.1877,
>          0.2190,  1.2190,  2.2190,  3.2190,  4.2190,  5.2190,  6.2190,  7.2190,
>          8.2190,  9.2190, 10.2190, 11.2190, 12.2190, 13.2190, 14.2190, 15.2190,
>          0.2502,  1.2502,  2.2502,  3.2502,  4.2502,  5.2502,  6.2502,  7.2502,
>          8.2502,  9.2502, 10.2502, 11.2502, 12.2502, 13.2502, 14.2502, 15.2502,
>          0.2815,  1.2815,  2.2815,  3.2815,  4.2815,  5.2815,  6.2815,  7.2815,
>          8.2815,  9.2815, 10.2815, 11.2815, 12.2815, 13.2815, 14.2815, 15.2815,
>          0.3128,  1.3128,  2.3128,  3.3128,  4.3128,  5.3128,  6.3128,  7.3128,
>          8.3128,  9.3128, 10.3128, 11.3128, 12.3128, 13.3128, 14.3128, 15.3128,
>          0.3441,  1.3441,  2.3441,  3.3441,  4.3441,  5.3441,  6.3441,  7.3441,
>          8.3441,  9.3441, 10.3441, 11.3441, 12.3441, 13.3441, 14.3441, 15.3441,
>          0.3754,  1.3754,  2.3754,  3.3754,  4.3754,  5.3754,  6.3754,  7.3754,
>          8.3754,  9.3754, 10.3754, 11.3754, 12.3754, 13.3754, 14.3754, 15.3754,
>          0.4066,  1.4066,  2.4066,  3.4066,  4.4066,  5.4066,  6.4066,  7.4066,
>          8.4066,  9.4066, 10.4066, 11.4066, 12.4066, 13.4066, 14.4066, 15.4066,
>          0.4379,  1.4379,  2.4379,  3.4379,  4.4379,  5.4379,  6.4379,  7.4379,
>          8.4379,  9.4379, 10.4379, 11.4379, 12.4379, 13.4379, 14.4379, 15.4379,
>          0.4692,  1.4692,  2.4692,  3.4692,  4.4692,  5.4692,  6.4692,  7.4692,
>          8.4692,  9.4692, 10.4692, 11.4692, 12.4692, 13.4692, 14.4692])

To me the better design is to assign 
`w = h = int(math.sqrt(x.shape[1])) # for square images `
and skip the first element of returned freqs_cis when applying rope:
`q[:, :, 1:], k[:, :, 1:] = apply_rotary_emb(q[:, :, 1:], k[:, :, 1:], freqs_cis=freqs_cis[1:,:]) `

**Comment by bhheo** [comment]
`x.shape[1]-1`, `q[:, :, 1:]`, and `k[:, :, 1:]` are used to exclude `cls_token` from rope embedding.
I think most ViT has `cls_token`

I assume inputs of `init_t_xy` are integers because number of tokens should be integer.
For simplicity, I write square image case but you can change it for your situation.

Because self-attn is a middle layer of transformer, it doesn’t include full details of model.
I recommend you to see `models/rope_vit.py` for details.
https://github.com/naver-ai/rope-vit/blob/main/models/vit_rope.py

**Comment by yuanzhi-zhu** [comment]
I see, thanks for reminding me
