### ISSUE TITLE
Would you mind sharing the script with the training args for the 400 epoch Deit training recipe?

### ISSUE THREAD

**Issue by SophieOstmeier** [naver-ai/rope-vit#5]
Hi, 
Would be curious to your training args to be able to use your training environment.
Thank you so much!
Sophie

**Comment by bhheo** [comment]
Hi

The training args for Deit 400 epochs can be found in the Deit `README.md`
https://github.com/naver-ai/rope-vit/blob/main/deit/README.md

If you want a script other than that, please let me know.

Best
Heo
