### ISSUE TITLE
About inference process

### ISSUE THREAD

**Issue by SmileShaun** [naver-ai/rope-vit#7]
Dear author, thank you very much for your work. I am a beginner in RoPE, please allow me to ask you a question that may seem very stupid.
During the inference process of the language model, we may need to specify the max token length to allow RoPE to perform extrapolation. In your implementation, are there any additional parameters I need to specify during inference? 

I am doing a dense prediction task, and the size of the training image is 256x256. Should I change end_x and end_y in init_t_xy() to 256 during training? Then re-specify the size of end_x and end_y (For example 512x512) during inference?

Thanks again and best wishes!

**Comment by bhheo** [comment]
Hi

Thank you for your interest in our work

If you want to change the image size, you should change `end_x` and `end_y`.

Like following lines
https://github.com/naver-ai/rope-vit/blob/c316aecc0be984dc3d23fa79c056da290be7a3ec/models/vit_rope.py#L188-L190
https://github.com/naver-ai/rope-vit/blob/c316aecc0be984dc3d23fa79c056da290be7a3ec/models/vit_rope.py#L198-L201

I think `end_x, end_y=256 // self.patch_size` for training and `end_x, end_y=512 // self.patch_size` might work well for your case.

Please let me know if you have any further questions.
